export REPOS="$HOME/repos"
export WORK_REPOS="$REPOS/black-cape"
export CONFIG="$HOME/.config"
export SCRIPTS="$CONFIG/scripts"
export NOTES="$HOME/Desktop/notes"
export HOMEBREW_BUNDLE_FILE="$CONFIG/Brewfile"
. "$HOME/.local/share/bob/env/env.sh"
. "$HOME/.cargo/env"
